#Triggers
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
defaults:
  run:
    working-directory: test
#Functions
jobs:
  #Build Job
  build:
    #Name of the job
    name: Build
    # The OS to run the job on
    runs-on: ubuntu-latest
    # Steps
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.19.x
          cache: npm
      - name: Install NPM Dependencies
        run: npm i
      - name: Upload artifact in order to deploy
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: test/dist
      - name: Display structure of uploaded files
        run: ls -R
  # Deploy Job
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: test/dist
      - name: Display structure of downloaded files
        run: ls -R
      - name: Deploy to gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          publish_dir: test/dist
